### ISSUE TITLE
What kind of environment, tensorflow version, GPU size, etc. are you using? Thank you.

### ISSUE THREAD

**Issue by tjnkyqcy** [petrosDemetrakopoulos/LSTM-radar-precipitation-forecast#1]
What kind of environment, tensorflow version, GPU size, etc. are you using? Thank you.

**Comment by tjnkyqcy** [comment]
Where can I find a more detailed description of this method in a journal paper?

**Comment by petrosDemetrakopoulos** [comment]
Due to the high-level of complexity of the model and the large amount of data it was impossible to train it on my laptop. Thus, I trained it on a Google Colab notebook with the default Colab GPU configuration. 
Tensorflow 2.0 was used.

**Comment by petrosDemetrakopoulos** [comment]
Unfortunately there is no formal journal paper explaining the method, here is the article accompanying the implementation https://petrosdemetrakopoulos.medium.com/short-term-precipitation-forecasting-using-convolutional-lstm-neural-networks-f347db1b5f1d
