### ISSUE TITLE
What is the version of python

### ISSUE THREAD

**Issue by tjnkyqcy** [petrosDemetrakopoulos/LSTM-radar-precipitation-forecast#3]
What is the version of python，After installing pygmt, the following error is also reported：
pygmt.exceptions.GMTCLibNotFoundError: Error loading GMT shared library at 'gmt.dll'.
Error loading GMT shared library at 'gmt_w64.dll'.
Error loading GMT shared library at 'gmt_w32.dll'.

I think it might have something to do with the version of python.

**Comment by petrosDemetrakopoulos** [comment]
I personally run it with Python 3.8.15 locally. The error message appears coming from a Windows system (mentions .dll files) and as I do not use Windows I am afraid I cannot further help.
